moved X related code to x-setup script

diff --git a/scripts/x-setup b/scripts/x-setup
--- a/scripts/x-setup
+++ b/scripts/x-setup
@@ -4,11 +4,40 @@
 #
 # Written by cmacrae 21/07/13
 
-# Check for root
-if [ $EUID -ne 0 ]; then
-  echo "This script must be run as root!"
+# Ensure script is not being run with root privileges
+if [ $EUID -eq 0 ]; then
+   echo "Please don't run this script with root priveleges!"
+   exit 1
+fi
+
+# Ensure script is being run in Terminal.app (due to launchctl restrictions)
+if [ $TERM_PROGRAM != "Apple_Terminal" ]; then
+  echo "This script must be run in Apple's Terminal.app"
+  echo "Please re-run this script in Terminal.app..."
   exit 1
 fi
+
+# Ensure the user is running this script on OS X
+if [ $(uname -s) != "Darwin" ]; then
+    echo "This script is for use with OS X!"
+    exit 1
+fi
+
+# Safe run function to ensure commands are executed successfully
+saferun() {
+  typeset cmnd="$*"
+  typeset ret_code
+
+  eval  $cmnd
+  ret_code=$?
+  
+  if [ $ret_code != 0 ]; then
+     echo -e ""$RED_UL"\n\nIt looks like there was an issue "$ERR_MSG"!"$ESC"\n\nExiting..."
+     exit $?
+  fi
+}
+
+
 
 # Set library path
 LIB_PATH=/Users/$USER/Library/LaunchAgents
@@ -40,7 +69,6 @@ YELLOW='\033[38;33m'
 YELLOW_UL='\033[38;4;33m'
 
 # Title
-clear
 MESSAGE=""$BLUE_UL"X11 Setup"$ESC""
 title
 cat << EOM
@@ -55,7 +83,28 @@ EOM
 read -r -p "Press [Enter] to continue..."
 echo ''
 
-# Create a service file to be enabled to run at login to start X with the above script
+# Fetch & install XQuartz if it isn't already installed
+if [ ! -d /Applications/Utilities/XQuartz.app ]; then
+  echo 
+  ERR_MSG="retrieving the XQuartz disk image"
+  echo "Fetching XQuartz..."
+  saferun curl -s -o /tmp/xquartz.dmg http://xquartz-dl.macosforge.org/SL/XQuartz-2.7.6.dmg
+  sudo -v # Keep sudo authentication open
+  ERR_MSG="mounting the XQuartz disk image"
+  echo "Mounting XQuartz disk image..."
+  saferun hdiutil mount -mountpoint /Volumes/xquartz /tmp/xquartz.dmg 1>/dev/null # Mount XQuartz disk image, safely should failure occur
+  ERR_MSG="installing XQuartz"
+  echo "Installing XQuartz..."
+  saferun sudo installer -pkg /Volumes/xquartz/XQuartz.pkg -target /
+  echo -e "\n"$GREEN"XQuartz installed successfully!"$ESC""
+  umount /Volumes/xquartz 2>&1 > /dev/null
+  echo
+elif [ -d /Applications/Utilities/XQuartz.app ]; then
+  echo 
+  echo -e "\n"$GREEN"It looks like XQuartz is already installed..."$ESC""
+fi
+
+# Set up startx launchd script
 echo -e "Setting up X11 launchd service..."
 if [ ! -d $LIBPATH ]; then
   mkdir -p $LIBPATH
@@ -73,8 +122,8 @@ do
     case $ANSWER in
       [yY][eE][sS]|[yY])
         echo -e "\nOK, disabling Finder..."
-        defaults write com.apple.finder QuitMenuItem -bool YES
-        sudo -u $USER launchctl unload -w /System/Library/LaunchAgents/com.apple.Finder.plist
+        sudo defaults write com.apple.finder QuitMenuItem -bool YES
+        launchctl unload -w /System/Library/LaunchAgents/com.apple.Finder.plist
         break
         ;;
       [nN][oO]|[nN])
@@ -93,8 +142,8 @@ while :
       case $ANSWER in
         [yY][eE][sS]|[yY])
           echo -e "\nOK, hiding Dock.app..."
-          defaults write com.apple.dock autohide-time-modifier -int 10000000000
-          defaults write com.apple.dock no-bouncing -bool TRUE
+          sudo defaults write com.apple.dock autohide-time-modifier -int 10000000000
+          sudo defaults write com.apple.dock no-bouncing -bool TRUE
           killall Dock
           break
           ;;
@@ -109,12 +158,12 @@ done
 
 # Hide menu bar for XQuartz
 echo -e "Configuring XQuartz to be seemless..."
-mv /Applications/Utilities/XQuartz.app/Contents/Info.plist{,.orig} ; cp -f /tmp/saveosx/xquartz.plist /Applications/Utilities/XQuartz.app/Contents/Info.plist
+sudo mv /Applications/Utilities/XQuartz.app/Contents/Info.plist{,.orig} 2>&1 > /dev/null ; sudo cp -f /tmp/saveosx/xquartz.plist /Applications/Utilities/XQuartz.app/Contents/Info.plist
 
 # Set XQuartz to launch at login
 echo ''
 echo -e "Necessary X files have been created.\n"$YELLOW"Setting X to launch at login"$ESC""
-sudo -u $USER launchctl load -w $LIB_PATH/org.saveosx.startx.plist
+launchctl load -w $LIB_PATH/org.saveosx.startx.plist
 echo ''
 echo -e ""$GREEN"Complete!"$ESC""
 read -r -p "Press [Enter] to continue... "
